### PR TITLE
Update readme to use python3.7

### PR DESCRIPTION
**Pull request by Br3nda**
The readme says we need to use Python 3.7, but then has instructions that ask for python 2.7

### CODE REVIEW

**Comment by Br3nda** [comment]
Should we remove circle ci build in 2. 7 also?

**Comment by Morendil** [comment]
@Br3nda Yes! There's no great rush but eventually we're planning to remove all Python 2 compatibility arrangements.

**Comment by Br3nda** [comment]
I'm helping Australia set up. I'll send some PRs as i find stuff. The circle ci doesn't pass out of the box either, not on python 2 or 3.

**Comment by Morendil** [comment]
@Br3nda Thanks! Let me know if you'd like me to look at the repo/CI output for Australia, possibly it's stuff we've already seen before.

**Comment by Br3nda** [comment]
https://circleci.com/gh/digitalnsw/openfisca-nsw

The single.json and couple.json dont seem to be copied in `make build`, so at `make test` they're not found

**Pull request merged**
