### PR TITLE
Update numpy dependency version to 1.18

### PR DESCRIPTION
**Pull request by sandcha**
Connected to openfisca/openfisca-core#924

> To revert : CircleCI branch set to follow Core work in progress on numpy update.

---
* Technical improvement.
* Details:
  - Declare package compatible with OpenFisca-Core v35 that updates numpy dependency.
- - - -

These changes, coming with the numpy dependency update:

- Add a new feature (for instance adding a variable)
- Fix or improve an already existing calculation.

### CODE REVIEW

**Comment by benjello** [comment]
No `select`in this repo.

**Comment by benjello** [comment]
No linspace either.

**Comment by benjello** [comment]
@sandcha : if there is more to check feel free to assign me ;-)

**Review by benjello — APPROVED** [review]

**Comment by benjello** [comment]
@sandcha LGTM

**Comment by sandcha** [comment]
Rebase coming + fix on revision bump from 3.10 to 3.11.

**Comment by sandcha** [comment]
Reverting CI config and squashing commits.

**Pull request merged**
